title: Quantitive Analysis for Trading
description: Studying algebra as well as trading strategy
author: Hakase Kong
avatar: /100324이찬빈_1.jpg
email: piscu@g.skku.edu
# location: 10
# skin: 10
# date_format: 10
# subscribe: 10

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  
paginate: 10
# google_analytics: 10
# disqus: 10

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag
# =========================
facebook:
  username: Chanbin Lee
  card: summary
logo: logo.png
instagram:
  name: Chanbin Lee
  links: https://instagram.com/b2_nii
social: GitHub
  url: https://github.com/Hakase-Kong/Hakase-Kong
title: Naver
  url: https://kin.naver.com/profile/index.naver?u=SFYWO6QJg73UnGImd%2Fhl%2F%2Bw7qNk2f9qn6NSbKRv0GN4%3D
google_site_verification: 
lang: en
