title: My Coding Canvas
description: Studying algebra as well as trading strategy
author: Hakase Kong
avatar: /100324이찬빈_1.jpg
email: piscu@g.skku.edu
location: 
skin: 
date_format: 
subscribe: 

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  
paginate: 10
google_analytics:
disqus:

exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

google_site_verification: 
lang: en
